name: plasmabio-Mineure_UE3
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - jupyterlab>=3.2,<4
  - jupyter-resource-usage
  - jupyterlab-topbar
  - jupyterlab-topbar-text
  - jupyterlab-system-monitor
  - nodejs
  - bash_kernel
  # ABN MODIF
  - r-irkernel
  - r-base>=4
  - r-tidyverse
  - pip:
